/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ColorPanel: typeof import('./src/components/color-panel.vue')['default']
    Icon: typeof import('./src/components/icon.vue')['default']
    JaTreeNode: typeof import('@janus-ui/lib/components/tree-node/src/tree-node.vue.js')['default']
  }
}
